#if !defined(MATERIAL_IDS_GLSL)
#define MATERIAL_IDS_GLSL
// This file was automatically generated by block_wrangler


bool materialIsWater(int id) {
	return id == 1010;
}


bool materialIsIce(int id) {
	return id == 1009;
}


bool materialIsLava(int id) {
	return id == 1008;
}


bool materialIsPlant(int id) {
	return id == 1001 || id == 1002 || id == 1004 || id == 1005 || id == 1006 || id == 1007;
}


struct Sway {int value;};
const Sway Sway_NONE = Sway(0);
const Sway Sway_UPPER = Sway(1);
const Sway Sway_LOWER = Sway(2);
const Sway Sway_HANGING = Sway(3);
const Sway Sway_FLOATING = Sway(4);
const Sway Sway_FULL = Sway(5);
Sway materialSwayType(int id) {
	if (id == 1006)
		return Sway_UPPER;
	if (id == 1005)
		return Sway_LOWER;
	if (id == 1003 || id == 1004)
		return Sway_HANGING;
	if (id == 1002)
		return Sway_FLOATING;
	if (id == 1001)
		return Sway_FULL;
	return Sway_NONE;
}


#endif // MATERIAL_IDS_GLSL