#ifndef MATERIAL_IDS_GLSL
#define MATERIAL_IDS_GLSL

#define MATERIAL_WATER 1001
#define MATERIAL_PLANTS 1002
#define MATERIAL_LEAVES 1003
#define MATERIAL_TALL_PLANT_UPPER 1004
#define MATERIAL_TALL_PLANT_LOWER 1005

#endif // MATERIAL_IDS_GLSL