#ifndef MATERIAL_IDS_GLSL
#define MATERIAL_IDS_GLSL

#define MATERIAL_WATER 1001
#define MATERIAL_PLANTS 1002
#define MATERIAL_LEAVES 1003
#define MATERIAL_GRASS_BLOCK 1004

#endif // MATERIAL_IDS_GLSL